import { Professional } from "@/types";

export const professionals: Professional[] = [
  {
    id: "1",
    name: "Johnathan Doe",
    title: "Lead Home Inspector",
    rating: 4.5,
    reviews: 124,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDj_hsodP2z9sgsqZh9zHDELX8yzay0LrenBu4N6_kHgsnR0f5j-Be_7--4waIkw8iqMhioiJ2dnXca_TEQx8cgsaaHomQDelQxJU_8cWinhAa2pSgk238jbVxrp7wG9dYQVACyM2AahDtvkb3CA-1k4IsO6eJpqdqBhfggkuOlAjlyYpAbu-qV4o9-90mdwkxSx2azaIZwINighRb-R9EnMbyIlISepVHximV5fNkZPAZvNRMejpIdyjB5IGkRAEG2SnMKm6rkrfmZ",
    specialty: "Residential Inspections",
    location: "New York, NY",
    specialtyIcon: "home_pin",
  },
  {
    id: "2",
    name: "Sarah Miller",
    title: "Real Estate Photographer",
    rating: 5,
    reviews: 98,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCae3axwoic0xMLjVzwqeAFFZ6eQRXFYszDYTE2bgYJOm5k0k2UExxtNaqshdycHtwURJkeIxqR0ps1hEfQfsmeHpfQZQIs4S_12O2LVDR07c6cezUSKXW21Ehk3uV2AO0hnkWagzBGb8yCUKVCVI1SLvmWedW-kqsKEjCcGi99Af2UfBQRVipQgvoTs40h06A136ynbb8b-v1iup5VWTPw30ejRf0p_ObUpTfXXkRvct2_KrcDX0b0rbZS28zTqJFmlgY8k4YeaEg_",
    specialty: "Luxury Property Shoots",
    location: "Los Angeles, CA",
    specialtyIcon: "photo_camera",
  },
  {
    id: "3",
    name: "Mike Chen",
    title: "Mortgage Broker",
    rating: 4,
    reviews: 210,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBkPGR6YiA_LflaUAR_qxki2hPey0FsfSAmr0m45Ri0B45nL7ySGZlLj1J37_P54A9yWdqmlfDG2LfAUEdhrJKKemcXPakSaA66GzkGydOFWILRHp3OQ-Xb1N5kbsAlJlnNa2h_ht4gC0AiG7z_KGftWcYMaoCjK9b9evYpa_zy8z9my9BYqu-3oSaqVe9nNZrifgkfhcj5NHbcHoaOqQyYxMHMMOHUKFjcDlj8wXyPp7qaueAIOKl5s3iSNKwtLxCbrHABfObkRHzo",
    specialty: "First-Time Home Buyers",
    location: "Chicago, IL",
    specialtyIcon: "account_balance",
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    title: "Real Estate Lawyer",
    rating: 5,
    reviews: 85,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDMZ8ooJyLKl5VbBP9OWM1sKMW6I2x3olB0Dl0mxe-JcEndeZnITkdI7oZ-DIxmnRlAyllrayDloI5b69S8OoaVMZ_lyme8UFWOLZJE6JYR1oKQbTvF_e43PGW5Kyz9UUg6REsGqtKxbnfhum5ASMLy0mHOTOPL2WJkTRaO5sQpSFcs1EiG0NB9BTfAh7p6cA2NgZXvtqfpSsxM7YJKai28m6oeZiJQnfW78Iti_JD7FFbdLgB0nCb1F5lV4S5IbJEivdiJUbnIAaBW",
    specialty: "Contract Law & Closings",
    location: "Miami, FL",
    specialtyIcon: "gavel",
  },
  {
    id: "5",
    name: "David Lee",
    title: "Home Staging Expert",
    rating: 4.5,
    reviews: 52,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBLEd8hqdO-cmJqNdEuaUWiFYjQn8QeCy5ukYKnGJHKAyQeouUYdKj0pW3LZWSH3PC6juxi6agWGJ98HEcyPM7wTLdLWxeo9s2qUDat69bXl0yOGY30Q_uMclQrNBTz_HgtqFDor5iWIRulZHcEZOnKjynaCtkEbkTPAlGtWQdmK03SQLOw9blQRGyGQT23-QxbPpO659EaqhlfTsRLapd6wUzzsBOumU3hBSVI1XbHZCtbKh2VKHlGNSo04bRtgIJigBsmATyO1pve",
    specialty: "Modern & Minimalist Design",
    location: "Austin, TX",
    specialtyIcon: "chair",
  },
  {
    id: "6",
    name: "Jessica Wu",
    title: "Moving Company Owner",
    rating: 5,
    reviews: 341,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC19WqX3WORHPR4Lgaw5vFh8QuLNrcrY5r9mn8JSzzVDiRaLjejfGcf_g92CJnCrJXafAkZS8sCk5t4Nq7dNxpbCCCQH1lHFn9czbnTI6jdyHe4_K0UXjHU-3bW6JzeX5d8ycgyIlUcCiK4isYdRFb61ZpBH3LM4AzR-HXaTklypYXXxV-5jxYwoh6iNGA1VnBAaLKh4w8t3rtwtLTM6zPxHjZG0ENAo3zUeUj_q5ekP6eu_40KHN1g-s0cSeZtIg2lh6PfTOgp-Mxy",
    specialty: "Long-Distance Relocation",
    location: "Nationwide",
    specialtyIcon: "local_shipping",
  },
];

export const categories = [
  "All",
  "Photographers",
  "Lawyers",
  "Stagers",
  "Home Inspectors",
  "Mortgage Brokers",
];

